services:
  backend:
    container_name: bookstore-backend
    build: 
      context: .
      dockerfile: app/django/Dockerfile
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/backend/bookstore
    depends_on:
      - db
    restart: "always"
      
  db:
    container_name: bookstore-api-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_USER: bookstore-user
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: bookstore-pass
      MYSQL_DATABASE: bookstore-django
    ports:
      - "3333:3306"
    volumes:
      - data:/var/lib/mysql
    restart: "always"
  
  frontend:
    container_name: bookstore-frontend
    build:
      context: .
      dockerfile: app/nextjs/Dockerfile
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    links:
      - backend
    restart: "always"

volumes:
  data: