# Generated by Django 4.0 on 2024-03-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymangas', '0002_remove_manga_author_manga_volumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='mymangas.author')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='mymangas.manga')),
            ],
        ),
    ]
