# Generated by Django 4.0 on 2024-04-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymangas', '0003_authormanga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='was_read',
        ),
        migrations.AddField(
            model_name='manga',
            name='volumes_read',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
