# Generated by Django 4.0 on 2024-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymangas', '0004_remove_manga_was_read_manga_volumes_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='volumes_read',
            field=models.IntegerField(null=True),
        ),
    ]
