# Generated by Django 4.0 on 2024-03-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymangas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='author',
        ),
        migrations.AddField(
            model_name='manga',
            name='volumes',
            field=models.IntegerField(default=1),
        ),
    ]
