# Generated by Django 4.0 on 2024-04-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymangas', '0006_author_created_at_author_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymangas.publisher'),
            preserve_default=False,
        ),
    ]
