# Generated by Django 4.0 on 2024-04-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymangas', '0007_manga_publisher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='MangaAuthor',
        ),
    ]
