# Generated by Django 4.0 on 2024-03-07 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0008_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='value',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='BookLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybooks.book')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybooks.literature')),
            ],
        ),
    ]
