# Generated by Django 4.0 on 2024-03-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0003_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='value',
            field=models.CharField(choices=[('GREAT', 'Great'), ('GOOD', 'Good'), ('MODERATE', 'Moderate'), ('BAD', 'Bad'), ('HORRIBLE', 'Horrible')], default='GOOD', max_length=10),
            preserve_default=False,
        ),
    ]
