# Generated by Django 4.0 on 2024-03-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0004_classification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='to_buy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], default='No', max_length=5),
        ),
    ]
