# Generated by Django 4.0 on 2024-03-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0009_alter_literature_value_bookliterature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookliterature',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_literatures', to='mybooks.book'),
        ),
    ]
