# Generated by Django 4.0 on 2024-03-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0012_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='mybooks.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybooks.genre')),
            ],
        ),
    ]
