# Generated by Django 4.0 on 2024-03-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0014_book_times_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=20, null=True)),
                ('pages', models.IntegerField(default=1)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybooks.format')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mybooks.publisher')),
            ],
        ),
    ]
