# Generated by Django 4.0 on 2024-03-20 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0015_book_pages_alter_author_name_alter_format_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='book',
            field=models.ForeignKey(default=182, on_delete=django.db.models.deletion.CASCADE, to='mybooks.book'),
            preserve_default=False,
        ),
    ]
