# Generated by Django 4.0 on 2024-04-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0019_alter_edition_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='mybooks.book')),
            ],
        ),
    ]
