# Generated by Django 4.0 on 2024-04-18 13:39

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0022_alter_bookliterature_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookliterature',
            name='unique-book-literature',
        ),
        migrations.AddConstraint(
            model_name='bookliterature',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('book'), django.db.models.functions.text.Lower('literature'), name='unique-book-literature'),
        ),
    ]
