# Generated by Django 4.0 on 2024-03-08 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0010_alter_bookliterature_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='mybooks.author'),
        ),
        migrations.AlterUniqueTogether(
            name='bookliterature',
            unique_together={('book', 'literature')},
        ),
    ]
