# Generated by Django 4.0 on 2024-03-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0013_bookgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_read',
            field=models.IntegerField(default=1),
        ),
    ]
