# Generated by Django 4.0 on 2024-03-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0017_remove_edition_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
