# Generated by Django 4.0 on 2024-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0021_author_created_at_author_updated_at_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookliterature',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookliterature',
            constraint=models.UniqueConstraint(fields=('book', 'literature'), name='unique-book-literature'),
        ),
    ]
